###########################################
## makeCacheMatrix(x)
## 	x - square matrix with nonzero determinant
## Generates a wrapper object for the matrix x 
## that caches its inverse. The resulting object
## has the following attributes:
##	g() returnes matrix
##	setinversematrix() caches the inverse matrix
##	getinversematrix() returnes the cached inverse matrix 
makeCacheMatrix <- function(x = matrix()) {
	
	inv <- NULL

	set <- function(y) {
		x <<- y      	## We modify x stored in the parent frame
		inv <<- NULL 	## inverse matrix is no longer valid
	}
	
	get <- function() x
	setinverse <- function(invmat) inv <<- invmat
	getinverse <- function() inv
	
	list(set = set, 
		get = get, 
		setinversematrix = setinverse, 
		getinversematrix = getinverse)
}


###########################################
## cacheSolve(x)
## 	x - an object generated by makeCacheMatrix(x)
## Returnes an inverse matrix for the one stored in x 
## using a cashed copy if available 
cacheSolve <- function(x) {

	inv <- x$getinversematrix()
	
	if (!is.null(inv)) {
		message("Getting cached data");
		return(inv);
	}
	
	data <- x$get()
	inv <- solve(data)
	x$setinversematrix(inv)
	inv	
}
